spring:
  security:
    user:
      name: local
      password: 123123

eureka:
  instance:
    instanceId: discovery
    hostname: localhost
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  endpoints:
    health:
      enabled: true
    web:
      exposure:
        include: info, health, metrics, prometheus
